### ISSUE TITLE
The userstyle applies to every website

### ISSUE THREAD

**Issue by thismoon** [mustafakhalaf-git/quran#1]
the userstyle applies to every website despite the `domain("quran.com")`

![image](https://user-images.githubusercontent.com/107642606/213859415-a8a5031d-7bd8-44a6-a2ac-8e768b18d9f9.png)
![image](https://user-images.githubusercontent.com/107642606/213859434-da317e67-d06a-497a-bef4-c6cc34797c1b.png)

**Comment by mustafa-archived** [comment]
For me it doesn't, themes work just fine on other sites, also I'm pretty sure discord doesn't have a --shade variable in it's css
![Screenshot_20230121-140135_Fennec](https://user-images.githubusercontent.com/42213155/213864005-431379c2-a370-4285-aee1-d603392a4d22.jpg)

Try reinstalling the css, I think you're a bit out of date + I updated the contrast of the background image

**Comment by thismoon** [comment]
![image](https://user-images.githubusercontent.com/107642606/213864290-60d9998e-df0f-4660-97d1-5916b2dcee12.png)

**Comment by mustafa-archived** [comment]
Oh yeah, I modified that, the version code was 1.3.7 ~~(because I copied the same version number from thr YT theme)~~, I changed it back to 1.0.0 then later 1.0.1

**Comment by thismoon** [comment]
updated to 1.0.1, problem is still present.
the theme applies to every website, here's a screenshot of the theme active in example.org
![image](https://user-images.githubusercontent.com/107642606/213864383-3eaea082-5654-4a96-a1b8-bd35384276b4.png)
even the macchiato flavor you showed in the screenshot still applies to everything
![image](https://user-images.githubusercontent.com/107642606/213864481-64fe2e34-99e8-4747-95f3-dcf8b9f9a937.png)
are you sure this is the version on github?

edit: it shows only quran.com on the stylus installed styles page, but when you visit the [installation url](https://raw.githubusercontent.com/mustafakhalaf-git/quran/main/src/QuranCatppuccinMacchiato.user.css) you find that it applies to everything too

**Comment by mustafa-archived** [comment]
oh wait I was looking at manage themes tab, css tab shows it applies to everything

**Comment by mustafa-archived** [comment]
But the discord thing is still unrelated to it, the discord theme works fine with me, sometimes discord needs a page refresh to make it load the theme though

**Comment by thismoon** [comment]
I mean what if a website (not quran.com) uses the variable --shade-8? the userstyle will replace it therefore this problem should be solved
here's an example of me wanting to make a green square and a blue square but the blue one color got replaced due to the userstyle
![image](https://user-images.githubusercontent.com/107642606/213864964-ee21a900-7ed0-4e89-b5e9-6a82ed84bcb6.png)
![image](https://user-images.githubusercontent.com/107642606/213864969-8e369a59-8d56-4b5a-b093-f5ee33d0f017.png)
sorry about the light text editor lol i just googled online html editor

**Comment by mustafa-archived** [comment]
I'm working on fixing it, but like said discord is unrelated

**Comment by mustafa-archived** [comment]
Yeah okay I found a fix, I need to insert the things in the bottom inside the domain

**Comment by mustafa-archived** [comment]
@thismoon done

**Comment by mustafa-archived** [comment]
also updated version code

**Comment by mustafa-archived** [comment]
Closing as it's been fixed
